{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f9400c07_d7519ea4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 15334
      },
      "writtenOn": "2024-04-05T14:32:15Z",
      "side": 1,
      "message": "I think this might, _finally_, be ready for review",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6ba1c610_a34cbd2d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 15334
      },
      "writtenOn": "2024-04-06T08:55:58Z",
      "side": 1,
      "message": "recheck mistake on the earlier manila patch revision",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6bfaa072_1d1c1ddd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 13252
      },
      "writtenOn": "2024-04-07T06:26:05Z",
      "side": 1,
      "message": "yay, so if manila manages to merge the stack soon, we might be able to merge this and get the remaining projects to fix their stuff within this cycle",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "7ddbf0cb_a699da12",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 16643
      },
      "writtenOn": "2024-04-08T22:46:49Z",
      "side": 1,
      "message": "Finally a +1 on behalf of manila folks; wouldn\u0027t be possible with all the direction and hard work you Stephen! Thank you",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "9cbee748_80ba4149",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 8313
      },
      "writtenOn": "2024-04-09T09:19:28Z",
      "side": 1,
      "message": "I think around Networking we are ready for this",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4ba4cf48_7d264a7b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 1131
      },
      "writtenOn": "2024-04-09T22:58:46Z",
      "side": 1,
      "message": "Should be good for neutron as our sqlalchemy master job is already green.",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "f8734aef_e7d4417c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 13252
      },
      "writtenOn": "2024-04-12T08:25:15Z",
      "side": 1,
      "message": "So manila is ready, I do however worry about projects that are not covered by cross-testing of this repo. Should we at least announce this bump happening on the ML? And possibly give them at least a couple of days to be able to check things?",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ab34e947_28d11e96",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 15334
      },
      "writtenOn": "2024-04-12T10:40:54Z",
      "side": 1,
      "message": "I already did it.\n\nhttps://lists.openstack.org/archives/list/openstack-discuss@lists.openstack.org/thread/RBHXHTO3GUOOXVSZXD4C2O3TKDOH2QSC/",
      "parentUuid": "f8734aef_e7d4417c",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c1008135_ecf3283b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 9816
      },
      "writtenOn": "2024-04-14T17:00:31Z",
      "side": 1,
      "message": "+1 from heat.\n\nHowever it seems there is a problem in Octavia we have to fix. See \nhttps://zuul.opendev.org/t/openstack/build/77653d12aac244368428f188081db0fa\n\n```\n2024-04-12 11:04:49.332750 | controller | \u001b[01;31mCRITICAL octavia-db-manage [\u001b[00;36m-\u001b[01;31m] \u001b[01;35m\u001b[01;31mUnhandled error\u001b[00m: TypeError: Additional arguments should be named \u003cdialectname\u003e_\u003cargument\u003e, got \u0027autoload\u0027\n2024-04-12 11:04:49.332785 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00mTraceback (most recent call last):\n2024-04-12 11:04:49.332803 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/bin/octavia-db-manage\", line 10, in \u003cmodule\u003e\n2024-04-12 11:04:49.332816 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    sys.exit(main())\n...\n2024-04-12 11:04:49.333229 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/octavia/octavia/db/migration/alembic_migrations/versions/3b199c848b96_create_no_monitor_operational_status.py\", line 33, in upgrade\n2024-04-12 11:04:49.333240 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    sa.Table(\u0027operating_status\u0027, md, autoload\u003dTrue, autoload_with\u003dbind)\n2024-04-12 11:04:49.333295 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"\u003cstring\u003e\", line 2, in __new__\n2024-04-12 11:04:49.333307 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py\", line 281, in warned\n2024-04-12 11:04:49.333319 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n2024-04-12 11:04:49.333330 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 431, in __new__\n2024-04-12 11:04:49.333345 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    return cls._new(*args, **kw)\n2024-04-12 11:04:49.333359 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 485, in _new\n2024-04-12 11:04:49.333370 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    with util.safe_reraise():\n2024-04-12 11:04:49.333382 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n2024-04-12 11:04:49.333393 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    raise exc_value.with_traceback(exc_tb)\n2024-04-12 11:04:49.333404 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 481, in _new\n2024-04-12 11:04:49.333416 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    table.__init__(name, metadata, *args, _no_init\u003dFalse, **kw)\n2024-04-12 11:04:49.333427 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 855, in __init__\n2024-04-12 11:04:49.333440 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    self._extra_kwargs(**kw)\n2024-04-12 11:04:49.516191 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 1003, in _extra_kwargs\n2024-04-12 11:04:49.516232 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    self._validate_dialect_kwargs(kwargs)\n2024-04-12 11:04:49.516247 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m  File \"/opt/stack/data/venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py\", line 596, in _validate_dialect_kwargs\n2024-04-12 11:04:49.516283 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00m    raise TypeError(\n2024-04-12 11:04:49.516296 | controller | ERROR octavia-db-manage \u001b[01;35m\u001b[00mTypeError: Additional arguments should be named \u003cdialectname\u003e_\u003cargument\u003e, got \u0027autoload\u0027\n```",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b2b34217_5ab98c87",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 9816
      },
      "writtenOn": "2024-04-14T17:17:58Z",
      "side": 1,
      "message": "I\u0027ve pushed a fix for octavia. https://review.opendev.org/c/openstack/octavia/+/915772 Alternatively we can merge this bump anyway and we can make a clean fix.",
      "parentUuid": "c1008135_ecf3283b",
      "revId": "1fa7310c079bdfbf7aaf8e9d561adcd36c91620e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}