{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8cc0f41d_1d948dd6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 15334
      },
      "writtenOn": "2022-07-14T15:19:07Z",
      "side": 1,
      "message": "We need this to be able to use python-ldap on Fedora 34 [1]. I\u0027m just proposing this to see what\u0027s causing the hold up\n\n[1] https://github.com/python-ldap/python-ldap/pull/458",
      "revId": "329f5e52331700629d4f194114636b46bfb247aa",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}