{
  "comments": [
    {
      "key": {
        "uuid": "bf51134e_2dbe25d4",
        "filename": "upper-constraints.txt",
        "patchSetId": 2
      },
      "lineNbr": 459,
      "author": {
        "id": 28522
      },
      "writtenOn": "2020-07-17T10:24:44Z",
      "side": 1,
      "message": "hmmm I\u0027m not convinced",
      "range": {
        "startLine": 459,
        "startChar": 0,
        "endLine": 459,
        "endChar": 21
      },
      "revId": "a04292d92efd30d032c18ddeb03bb05940effc0c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "bf51134e_ced4bcbe",
        "filename": "upper-constraints.txt",
        "patchSetId": 2
      },
      "lineNbr": 459,
      "author": {
        "id": 14288
      },
      "writtenOn": "2020-07-17T15:50:22Z",
      "side": 1,
      "message": "debian/ubuntu bug because they mess with package metadata incorrectly\nhttps://github.com/pypa/pip/issues/4022\n\nit\u0027s been exposed because of the setuptools update now has two codepaths (I think)",
      "revId": "a04292d92efd30d032c18ddeb03bb05940effc0c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "bf51134e_e9f6da90",
        "filename": "upper-constraints.txt",
        "patchSetId": 2
      },
      "lineNbr": 459,
      "author": {
        "id": 28522
      },
      "writtenOn": "2020-07-17T16:29:42Z",
      "side": 1,
      "message": "Ok I seen thanks",
      "parentUuid": "bf51134e_ced4bcbe",
      "revId": "a04292d92efd30d032c18ddeb03bb05940effc0c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}